"""
Virtual Reality Spring 2026
Project 1 course-provided implementation file

Mufeng Zhu (TA), Spring 2025

Revised for Spring 2026 offering
"""

import cv2
import numpy as np
import open3d as o3d

import json

import argparse
import os

def point_cloud(depth, fov_x):
    # adapted from: https://blender.stackexchange.com/a/211600
    # Don't use any of the functions provided by Open3D
    # Don't use create_point_cloud_from_rgbd_image
    # Don't use the pinhole instrinsic parameters
    # I don't know why they are wrong, but they misalign

    # Distance factor from the camera focal angle
    factor = 2.0 * np.tan(fov_x / 2.0)

    rows, cols = depth.shape
    c, r = np.meshgrid(np.arange(cols), np.arange(rows), sparse=True)
    valid = (depth > 0)

    # Negate Z (the camera Z is at the opposite)
    z = -np.where(valid, depth, np.nan)
    ratio = max(rows, cols)
    x = -np.where(valid, factor * z * (c - (cols / 2)) / ratio, 0)
    y = np.where(valid, factor * z * (r - (rows / 2)) / ratio, 0)
    ones = np.ones_like(z)
    return np.dstack((x, y, z, ones))


def read_transparent_png_depth(filename):
    # for depth png only, very hacky
    # Code from https://stackoverflow.com/a/41896175

    image_4channel = cv2.imread(filename, cv2.IMREAD_UNCHANGED)

    # in the .png depth image generated by Blender, all 4 channels are the same
    depth_channel = image_4channel[:, :, 0]
    # normalize 16-bit depth
    depth_channel = depth_channel.astype(np.float32) / 65535.
    # print(np.max(depth_channel), np.min(depth_channel))

    # need to inverse and * 8, 8 is the max depth in generate_rgbd.py
    depth_channel_inv = (1. - depth_channel) * 8.
    # print(np.max(depth_channel_inv), np.min(depth_channel_inv))

    depth_channel_final = (depth_channel > 0) * depth_channel_inv
    return depth_channel_final.astype(np.float32)


def read_transparent_png(filename):
    # for color png only, not for depth
    # Code from https://stackoverflow.com/a/41896175

    image_4channel = cv2.imread(filename, cv2.IMREAD_UNCHANGED)

    alpha_channel = image_4channel[:, :, 3]
    bgr_channels = image_4channel[:, :, :3]

    rgb_channels = cv2.cvtColor(bgr_channels, cv2.COLOR_BGR2RGB)
    # print("rgb_channels:" , np.max(rgb_channels), np.min(rgb_channels))

    # White Background Image
    white_background_image = np.ones_like(rgb_channels, dtype=np.uint8) * 255

    # Alpha factor
    alpha_factor = alpha_channel[:, :, np.newaxis].astype(np.float32) / 255.0
    # print("alpha_factor: ", np.max(alpha_factor), np.min(alpha_factor))
    alpha_factor = np.concatenate((alpha_factor, alpha_factor, alpha_factor), axis=2)

    # Transparent Image Rendered on White Background
    base = rgb_channels.astype(np.float32) * alpha_factor
    white = white_background_image.astype(np.float32) * (1 - alpha_factor)
    final_image = base + white
    return final_image.astype(np.uint8)


def normalize(vector):
    return vector / np.linalg.norm(vector)


def parse_json_camera_info(camera_info, height, width, idx):
    fov_x = camera_info["camera_angle_x"]  # in radians
    fov_y = fov_x  # hacky here, assuming height == width

    for pose in camera_info["frames"]:
        if not idx in pose["file_path"]: continue

        print(idx)
        print(np.asarray(pose["transform_matrix"]))

        homo_matrix = np.asarray(pose["transform_matrix"])

        trans = homo_matrix[:3, 3]

        rot = homo_matrix[:3, :3]

        print("np.linalg.norm:", np.linalg.norm(rot, axis=0), np.linalg.norm(rot, axis=1))

        break

    return rot, trans, fov_x

def create_pcd_perspective(rgb_image_path, depth_image_path, camera_path, idx, noise=0):
    color = read_transparent_png(rgb_image_path)
    depth = read_transparent_png_depth(depth_image_path)

    height, width = color.shape[:2]

    with open(camera_path) as f:
        camera_info = json.load(f)

    rot, trans, fov_x = parse_json_camera_info(camera_info, height, width, idx)
    
    if noise > 0:
        # Add random noise to translation
        noise_vec = np.random.uniform(-noise, noise, 3)
        trans += noise_vec

    points = point_cloud(depth, fov_x)

    points = np.reshape(points, (points.shape[0] * points.shape[1], 4))

    # valid only when the z coordinate is not np.nan
    valid = ~np.isnan(points[:, 2])
    points = points[valid]

    extrinsic = np.eye(4)

    extrinsic[:3, :3] = rot
    extrinsic[:3, -1] = trans

    verts = np.dot(points, extrinsic[:3].T)

    color = np.divide(color.astype(np.float64), 255)
    color = np.reshape(color, (color.shape[0] * color.shape[1], 3))
    color = color[valid]

    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(verts)
    pcd.colors = o3d.utility.Vector3dVector(color)

    return extrinsic, pcd


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--views', type=int, default=20, help='Number of views to use')
    parser.add_argument('--output', type=str, default='reconstructed.ply', help='Output PLY filename')
    parser.add_argument('--voxel_size', type=float, default=0, help='Voxel size for downsampling (0 to disable)')
    parser.add_argument('--noise', type=float, default=0, help='Magnitude of random noise to add to camera translation (e.g. 0.01)')
    args = parser.parse_args()

    pcd_combined = o3d.geometry.PointCloud()
    camera_path = "step1_rgbd_data/transforms.json"
    
    n_views = args.views
    
    for i in range(0, n_views):
        rgb_image_path = 'step1_rgbd_data/r_'+str(i)+'.png'
        depth_image_path = 'step1_rgbd_data/r_'+str(i)+'_depth_0001.png'
        idx = 'r_'+str(i)
            
        extrinsic1, pc = create_pcd_perspective(rgb_image_path, depth_image_path, camera_path, idx, noise=args.noise)
        pcd_combined += pc

    # pcd_combined = pcd_combined.remove_duplicated_points()
    
    if args.voxel_size > 0:
        print(f"Downsampling with voxel size {args.voxel_size}...")
        pcd_combined = pcd_combined.voxel_down_sample(voxel_size=args.voxel_size)
        
    o3d.io.write_point_cloud(args.output, pcd_combined)
    # o3d.visualization.draw_geometries([pcd_combined])

if __name__ == "__main__":
    main()